### ISSUE TITLE
Can't run yarn

### ISSUE THREAD

**Issue by madeken** [bitauth/bitcoin-ts#21]
Doing a fresh git clone:

> $ yarn
> yarn install v1.12.3
> [1/5] 🔍  Validating package.json...
> [2/5] 🔍  Resolving packages...
> [3/5] 🚚  Fetching packages...
> error https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by bitjson** [comment]
Thanks for opening this issue! And sorry about that. 

This has been fixed in #9, everything should be cleaned up and working again now.
