### ISSUE TITLE
yarn error : event-stream-3.3.6.tgz not found

### ISSUE THREAD

**Issue by ArvsIndrarys** [bitauth/bitcoin-ts#26]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ x ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Referencing an error I got : `event-stream-3.3.6.tgz not found` when executing `yarn` as described, I found two solutions in [this issue](https://github.com/eclipse/che/issues/12077).

The solutions are : 
- removing the `yarn.lock` file
- adding to package.json that piece of code : 
```
  ...
  ,
  "resolutions": {
    "**/event-stream": "^4.0.1"
  }
```

Is it THAT necessary to have the yarn.lock file? Which one of these solutions are the best? I would then making a merge request with the chosen solution.

**Comment by bitjson** [comment]
Thanks for opening this issue! And sorry about the trouble installing. 

This has been fixed in #9, everything should be cleaned up and working again now.
